import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';

/// Halaman ini menggantikan fungsi Seeder lama.
/// Gunakan halaman ini untuk memperbaiki data Payment yang tidak sinkron.
class DataFixerScreen extends StatefulWidget {
  const DataFixerScreen({super.key});

  @override
  State<DataFixerScreen> createState() => _DataFixerScreenState();
}

class _DataFixerScreenState extends State<DataFixerScreen> {
  String _log = "Siap melakukan scanning data...\n";
  bool _isLoading = false;
  final FirebaseFirestore firestore = FirebaseFirestore.instance;

  // Fungsi untuk menambah log ke layar
  void _addLog(String text) {
    setState(() {
      _log += "$text\n";
    });
    debugPrint(text);
  }

  // --- LOGIKA UTAMA PERBAIKAN DATA ---
  Future<void> _fixPaymentStatus() async {
    setState(() => _isLoading = true);
    _log = ""; // Reset log
    _addLog("🚀 MEMULAI SCANNING & PERBAIKAN DATA...");

    int fixedCount = 0;
    int createdCount = 0;

    try {
      // 1. AMBIL SEMUA BOOKING YANG SUDAH COMPLETED
      // Kita hanya peduli pada booking yang statusnya sudah selesai/lunas
      final bookingSnapshot = await firestore
          .collection('bookings')
          .where('status', isEqualTo: 'Completed')
          .get();

      _addLog("📦 Ditemukan ${bookingSnapshot.docs.length} Booking 'Completed'. Memeriksa payments...");

      for (var bookingDoc in bookingSnapshot.docs) {
        final bookingId = bookingDoc.id;
        final userId = bookingDoc['userId'];
        
        // Cek apakah di booking status bayarnya sudah 'Paid'
        // (Kadang ada yang status Completed tapi paymentStatus null/Unpaid, kita anggap Paid karena sudah Completed)
        
        // 2. CARI PAYMENT PASANGANNYA
        final paymentQuery = await firestore
            .collection('payments')
            .where('bookingId', isEqualTo: bookingId)
            .get();

        if (paymentQuery.docs.isEmpty) {
          // KASUS A: DATA PAYMENT HILANG / BELUM DIBUAT
          _addLog("⚠️ Booking $bookingId: Payment TIDAK ADA. Membuat baru...");
          
          await firestore.collection('payments').add({
            'bookingId': bookingId,
            'userId': userId,
            'clinicId': bookingDoc['clinicId'],
            'amount': bookingDoc['grandTotal'] ?? 0,
            'status': 'Success', // Langsung Success
            'method': bookingDoc['paymentMethod'] ?? 'Tunai (Fixer)',
            'transactionDate': bookingDoc['scheduleDate'] ?? FieldValue.serverTimestamp(),
            'invoiceNumber': 'INV-FIX-${DateTime.now().millisecondsSinceEpoch}',
            'note': 'Generated by DataFixer',
          });
          
          createdCount++;
          _addLog("✅ Payment Baru Dibuat (Success).");

        } else {
          // KASUS B: DATA PAYMENT ADA, TAPI STATUS SALAH (PENDING/FAILED)
          for (var paymentDoc in paymentQuery.docs) {
            final currentStatus = paymentDoc['status'];
            
            if (currentStatus != 'Success') {
              _addLog("🛠️ Booking $bookingId: Status Payment '$currentStatus' -> Diperbaiki ke 'Success'");
              await paymentDoc.reference.update({'status': 'Success'});
              fixedCount++;
            }
          }
        }
      }

      _addLog("\n==========================================");
      _addLog("🏁 PROSES SELESAI!");
      _addLog("✅ Data Diperbaiki (Update): $fixedCount");
      _addLog("✅ Data Dibuat Baru (Create): $createdCount");
      _addLog("==========================================");

    } catch (e) {
      _addLog("❌ TERJADI ERROR: $e");
    } finally {
      setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Perbaikan Database", style: TextStyle(fontWeight: FontWeight.bold)),
        backgroundColor: Colors.red[700],
        foregroundColor: Colors.white,
      ),
      backgroundColor: Colors.grey[100],
      body: Column(
        children: [
          // Header Info
          Container(
            padding: const EdgeInsets.all(20),
            color: Colors.white,
            child: Column(
              children: [
                const Icon(Icons.healing, size: 50, color: Colors.red),
                const SizedBox(height: 10),
                const Text(
                  "Fitur ini akan mensinkronkan status 'Booking' dan 'Payment'.\nBooking yang sudah 'Completed' akan dipaksa memiliki Payment 'Success'.",
                  textAlign: TextAlign.center,
                  style: TextStyle(fontSize: 14, color: Colors.grey),
                ),
              ],
            ),
          ),
          
          // Area Log Terminal
          Expanded(
            child: Container(
              width: double.infinity,
              margin: const EdgeInsets.all(16),
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: Colors.black87,
                borderRadius: BorderRadius.circular(12),
              ),
              child: SingleChildScrollView(
                reverse: true, // Auto scroll ke bawah
                child: Text(
                  _log, 
                  style: const TextStyle(
                    color: Colors.greenAccent, 
                    fontFamily: 'monospace', 
                    fontSize: 12
                  ),
                ),
              ),
            ),
          ),

          // Tombol Aksi
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: SizedBox(
              width: double.infinity,
              height: 55,
              child: ElevatedButton.icon(
                onPressed: _isLoading ? null : _fixPaymentStatus,
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.red[700],
                  shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                ),
                icon: _isLoading 
                  ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
                  : const Icon(Icons.build_circle, color: Colors.white), 
                label: Text(
                  _isLoading ? "Sedang Memproses..." : "MULAI PERBAIKAN SEKARANG",
                  style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}