// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYMNuVPOycuk625zFG8cJSwA0pw0fwUHk',
    appId: '1:136116236412:web:26af7d1163616ebc6599f9',
    messagingSenderId: '136116236412',
    projectId: 'vesty-app-f54e9',
    authDomain: 'vesty-app-f54e9.firebaseapp.com',
    storageBucket: 'vesty-app-f54e9.firebasestorage.app',
    measurementId: 'G-JKGC99B377',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5NHdF5pIja-3XImzueSDeaGVW5goAL4I',
    appId: '1:136116236412:android:d021040068047e5c6599f9',
    messagingSenderId: '136116236412',
    projectId: 'vesty-app-f54e9',
    storageBucket: 'vesty-app-f54e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1FPAnsWw82KfJS_AoLaNUjkfHipgirUE',
    appId: '1:136116236412:ios:6f541946113748896599f9',
    messagingSenderId: '136116236412',
    projectId: 'vesty-app-f54e9',
    storageBucket: 'vesty-app-f54e9.firebasestorage.app',
    iosBundleId: 'com.example.vetsyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1FPAnsWw82KfJS_AoLaNUjkfHipgirUE',
    appId: '1:136116236412:ios:6f541946113748896599f9',
    messagingSenderId: '136116236412',
    projectId: 'vesty-app-f54e9',
    storageBucket: 'vesty-app-f54e9.firebasestorage.app',
    iosBundleId: 'com.example.vetsyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYMNuVPOycuk625zFG8cJSwA0pw0fwUHk',
    appId: '1:136116236412:web:5edee1e3647d8b8a6599f9',
    messagingSenderId: '136116236412',
    projectId: 'vesty-app-f54e9',
    authDomain: 'vesty-app-f54e9.firebaseapp.com',
    storageBucket: 'vesty-app-f54e9.firebasestorage.app',
    measurementId: 'G-CJD0FVFFM2',
  );
}
